services:
  web:
    build:
      context: ./app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-${COMPOSE_PROJECT_NAME}}
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=${DATABASE_HOST}
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASS=/run/secrets/db-user-pass
    #ports:
    #  - "80:80"
    secrets:
      - db-user-pass

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-pass
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db-user-pass
    #ports:
    #  - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - db-root-pass
      - db-user-pass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
