services:
  web:
    build:
      context: ./app
      target: development
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "80:80"
    secrets:
      - db-user-pass

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-pass
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db-user-pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - db-root-pass
      - db-user-pass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db-root-pass:
    file: ./db/mysql-root-pass.txt
  db-user-pass:
    file: ./db/mysql-user-pass.txt

volumes:
  db-data:
