services:
  web:
    build:
      context: ./app
      target: development
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-${COMPOSE_PROJECT_NAME}}
      - DB_HOST=${DATABASE_HOST}
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
    ports:
      - "80:80"
    secrets:
      - db-user-pass

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-pass
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_HOST}
      - MYSQL_PASSWORD_FILE=/run/secrets/db-user-pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - db-root-pass
      - db-user-pass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db-root-pass:
    file: ./db/db-root-pass.example.txt
  db-user-pass:
    file: ./db/db-user-pass.example.txt

volumes:
  db-data:
